### ISSUE TITLE
Module Sometimes Doesn't Work When rewrite_urls = 0

### ISSUE THREAD

**Issue by hartenthaler** [miqrogroove/family-tree-home#1]
I just installed your module on my test server. There are four trees. The module is visible in the control panel. No error. 

No function. When I log out and log in, I see "MyPage", not the page of any tree.

**Comment by miqrogroove** [comment]
I checked some of my other code hacks and couldn't reproduce that issue with my one tree config.  I will try adding a 2nd tree and see what happens with it.

**Comment by miqrogroove** [comment]
It still works here on my server with 2 trees.  So I need more info.  Could you describe your webtrees version, Family Tree Home Page version, do you have rewrite_urls in the config file, and are there any special privacy settings, such as guests can't see any trees?  Any other custom modules?  Also, if you could tell me anything about the address under the Sign In link, which sometimes ends with "%2Fmy-page" depending on the current page viewed.

**Comment by miqrogroove** [comment]
I was able to reproduce that bug.  Here are the criteria:

- Must have at least one tree visible to guests.
- Must have `rewrite_urls = "0"`
- Must click the Sign In link from the visitor's home/tree page.

Any other combination of settings or inputs would not trigger this bug.  It was tricky!

**Comment by hartenthaler** [comment]
Sorry for the late answer. I was busy, today. rewrite_urls was not set, so I assume it is used as "0". There is a tree visible to guests. And I signed in from the default tree home page. Now I will test your new version.

**Comment by hartenthaler** [comment]
Success! Now it works like expected. Great!

**Comment by RAMINCNZ** [comment]
What if one wants to keep pretty URLs??

Can the module be updated to allow for that??

Rick M
Nu Tirani - New Zealand
