### ISSUE TITLE
Upgrade family-tree-home for webtrees version 2.2

### ISSUE THREAD

**Issue by gudjonsi** [miqrogroove/family-tree-home#2]
Upgrade to family-tree-home to make it compatible with webtrees version 2.2 would be very much appreciated. Best regards.

**Comment by miqrogroove** [comment]
Thank you for the message.  I have not yet tested v2.2, so this module might work or might not.

In the meantime, if you'd like to add a "star" on the Code tab, that helps to boost the search results.  😁

**Comment by gudjonsi** [comment]
Thanks for the response. I've already tried the Family Tree Home Page v1.0.03 in webtrees 2.2.1 and errors appears, see in the enclosed text file. Regards.

[Family-Tree-Home-Page-Errors-wt-2-2-1.txt](https://github.com/user-attachments/files/17983293/Family-Tree-Home-Page-Errors-wt-2-2-1.txt)

**Comment by miqrogroove** [comment]
Good point.  I saw a message about that API change in the webtrees forum last week.  I guess it was a breaking change rather than a deprecation.
